param([string]$file)
$sql = (Get-Content $file) -join " "
$sql = $sql.ToUpper()
$sql = $sql -replace "\s+"," "
$sql = $sql -replace "\s*\)",")"
$sql = $sql -replace "\(\s*","("
$sql = $sql -replace "\s*=\s*"," = "
$sql = $sql -replace "\s*,\s*",", "
$sql = $sql -replace ",",",`r`n       "
$sql = $sql -replace "\s*SELECT "," SELECT "
$sql = $sql -replace "\(\s*SELECT","(`r`n SELECT"
$sql = $sql -replace "\s+CASE", "`r`n        CASE"
$sql = $sql -replace " WHEN", "`r`n           WHEN"
$sql = $sql -replace " ELSE", "`r`n          ELSE"
$sql = $sql -replace " END", "`r`n        END"
$sql = $sql -replace "\s*UPDATE "," UPDATE "
$sql = $sql -replace " FROM ","`r`n   FROM "
$sql = $sql -replace "\s*DELETE\s+FROM "," DELETE FROM "
$sql = $sql -replace " SET ","`r`n    SET "
$sql = $sql -replace " AS\s+SELECT ","`r`nAS`r`n SELECT "
$sql = $sql -replace " JOIN ","`r`n   JOIN "
$sql = $sql -replace " FULL ","`r`n   FULL "
$sql = $sql -replace " LEFT\s+","`r`n   LEFT "
$sql = $sql -replace " RIGHT ","`r`n RIGHT "
$sql = $sql -replace " INNER\s+JOIN ","`r`n  INNER JOIN "
$sql = $sql -replace " OUTER\s+JOIN "," OUTER JOIN "
$sql = $sql -replace " LEFT\s+JOIN "," LEFT JOIN "
$sql = $sql -replace " ON ","`r`n     ON "
$sql = $sql -replace " WHERE ","`r`n  WHERE "
$sql = $sql -replace " AND ","`r`n    AND "
$sql = $sql -replace " GROUP BY ","`r`n  GROUP BY "
$sql = $sql -replace " ORDER BY ","`r`n  ORDER BY "
$sql = $sql -replace " UNION ALL ","`r`n  UNION ALL`r`n "
$sql = $sql -replace ";",";`r`n"
$sql = $sql -replace "`r`n`r`n","`r`n"
Echo $sql